name: Janus Docker image

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-janus.yml'
      - 'docker/janus/Dockerfile'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-janus.yml'
      - 'docker/janus/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/janus
